// Code generated by "stringer -type=Opcode -linecomment"; DO NOT EDIT.

package jpath

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpSegmentStart-0]
	_ = x[OpSegmentEnd-1]
	_ = x[OpDescend-2]
	_ = x[OpSelectName-3]
	_ = x[OpSelectIndex-4]
	_ = x[OpSelectWildcard-5]
	_ = x[OpSelectArrayAll-6]
	_ = x[OpSelectSliceF00-7]
	_ = x[OpSelectSliceF10P-8]
	_ = x[OpSelectSliceF10N-9]
	_ = x[OpSelectSliceF01P-10]
	_ = x[OpSelectSliceF01N-11]
	_ = x[OpSelectSliceF11PP-12]
	_ = x[OpSelectSliceF11PN-13]
	_ = x[OpSelectSliceF11NP-14]
	_ = x[OpSelectSliceF11NN-15]
	_ = x[OpSelectSliceB00-16]
	_ = x[OpSelectSliceB10P-17]
	_ = x[OpSelectSliceB10N-18]
	_ = x[OpSelectSliceB01P-19]
	_ = x[OpSelectSliceB01N-20]
	_ = x[OpSelectSliceB11PP-21]
	_ = x[OpSelectSliceB11PN-22]
	_ = x[OpSelectSliceB11NP-23]
	_ = x[OpSelectSliceB11NN-24]
	_ = x[OpSelectSliceEmpty-25]
	_ = x[OpSelectFilter-26]
}

const _Opcode_name = "seg/start arg=endpcseg/enddescend/self+deepsel/namesel/indexsel/wildcardsel/array/allsel/slice/f00 step+ s0 e0sel/slice/f10p step+ s+ e0sel/slice/f10n step+ s- e0sel/slice/f01p step+ s0 e+sel/slice/f01n step+ s0 e-sel/slice/f11pp step+ s+ e+sel/slice/f11pn step+ s+ e-sel/slice/f11np step+ s- e+sel/slice/f11nn step+ s- e-sel/slice/b00 step- s0 e0sel/slice/b10p step- s+ e0sel/slice/b10n step- s- e0sel/slice/b01p step- s0 e+sel/slice/b01n step- s0 e-sel/slice/b11pp step- s+ e+sel/slice/b11pn step- s+ e-sel/slice/b11np step- s- e+sel/slice/b11nn step- s- e-sel/slice/empty step=0sel/filter"

var _Opcode_index = [...]uint16{0, 19, 26, 43, 51, 60, 72, 85, 110, 136, 162, 188, 214, 241, 268, 295, 322, 347, 373, 399, 425, 451, 478, 505, 532, 559, 581, 591}

func (i Opcode) String() string {
	if i >= Opcode(len(_Opcode_index)-1) {
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
